Sep 20 04:54:57 kind-worker2 systemd[1]: Condition check resulted in kubelet: The Kubernetes Node Agent being skipped.
Sep 20 04:56:05 kind-worker2 systemd[1]: Starting kubelet: The Kubernetes Node Agent...
Sep 20 04:56:05 kind-worker2 systemd[1]: Started kubelet: The Kubernetes Node Agent.
Sep 20 04:56:05 kind-worker2 kubelet[300]: Flag --container-runtime has been deprecated, will be removed in 1.27 as the only valid value is 'remote'
Sep 20 04:56:05 kind-worker2 kubelet[300]: Flag --pod-infra-container-image has been deprecated, will be removed in 1.27. Image garbage collector will get sandbox image information from CRI.
Sep 20 04:56:05 kind-worker2 kubelet[300]: Flag --provider-id has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Sep 20 04:56:05 kind-worker2 kubelet[300]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Sep 20 04:56:05 kind-worker2 kubelet[300]: Flag --cgroup-root has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Sep 20 04:56:05 kind-worker2 kubelet[300]: I0920 04:56:05.807001     300 server.go:193] "--pod-infra-container-image will not be pruned by the image garbage collector in kubelet and should also be set in the remote runtime"
Sep 20 04:56:05 kind-worker2 kubelet[300]: Flag --container-runtime has been deprecated, will be removed in 1.27 as the only valid value is 'remote'
Sep 20 04:56:05 kind-worker2 kubelet[300]: Flag --pod-infra-container-image has been deprecated, will be removed in 1.27. Image garbage collector will get sandbox image information from CRI.
Sep 20 04:56:05 kind-worker2 kubelet[300]: Flag --provider-id has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Sep 20 04:56:05 kind-worker2 kubelet[300]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Sep 20 04:56:05 kind-worker2 kubelet[300]: Flag --cgroup-root has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Sep 20 04:56:06 kind-worker2 kubelet[300]: I0920 04:56:06.766579     300 server.go:399] "Kubelet version" kubeletVersion="v1.24.7"
Sep 20 04:56:06 kind-worker2 kubelet[300]: I0920 04:56:06.766693     300 server.go:401] "Golang settings" GOGC="" GOMAXPROCS="" GOTRACEBACK=""
Sep 20 04:56:06 kind-worker2 kubelet[300]: I0920 04:56:06.767321     300 server.go:813] "Client rotation is on, will bootstrap in background"
Sep 20 04:56:06 kind-worker2 kubelet[300]: I0920 04:56:06.775271     300 dynamic_cafile_content.go:157] "Starting controller" name="client-ca-bundle::/etc/kubernetes/pki/ca.crt"
Sep 20 04:56:06 kind-worker2 kubelet[300]: I0920 04:56:06.800828     300 container_manager_linux.go:262] "Container manager verified user specified cgroup-root exists" cgroupRoot=[kubelet]
Sep 20 04:56:06 kind-worker2 kubelet[300]: I0920 04:56:06.800983     300 container_manager_linux.go:267] "Creating Container Manager object based on Node Config" nodeConfig={RuntimeCgroupsName: SystemCgroupsName: KubeletCgroupsName: KubeletOOMScoreAdj:-999 ContainerRuntime: CgroupsPerQOS:true CgroupRoot:/kubelet CgroupDriver:systemd KubeletRootDir:/var/lib/kubelet ProtectKernelDefaults:false NodeAllocatableConfig:{KubeReservedCgroupName: SystemReservedCgroupName: ReservedSystemCPUs: EnforceNodeAllocatable:map[pods:{}] KubeReserved:map[] SystemReserved:map[] HardEvictionThresholds:[]} QOSReserved:map[] ExperimentalCPUManagerPolicy:none ExperimentalCPUManagerPolicyOptions:map[] ExperimentalTopologyManagerScope:container ExperimentalCPUManagerReconcilePeriod:10s ExperimentalMemoryManagerPolicy:None ExperimentalMemoryManagerReservedMemory:[] ExperimentalPodPidsLimit:-1 EnforceCPULimits:true CPUCFSQuotaPeriod:100ms ExperimentalTopologyManagerPolicy:none}
Sep 20 04:56:06 kind-worker2 kubelet[300]: I0920 04:56:06.802984     300 topology_manager.go:133] "Creating topology manager with policy per scope" topologyPolicyName="none" topologyScopeName="container"
Sep 20 04:56:06 kind-worker2 kubelet[300]: I0920 04:56:06.803072     300 container_manager_linux.go:302] "Creating device plugin manager" devicePluginEnabled=true
Sep 20 04:56:06 kind-worker2 kubelet[300]: I0920 04:56:06.803464     300 state_mem.go:36] "Initialized new in-memory state store"
Sep 20 04:56:06 kind-worker2 kubelet[300]: I0920 04:56:06.843755     300 kubelet.go:376] "Attempting to sync node with API server"
Sep 20 04:56:06 kind-worker2 kubelet[300]: I0920 04:56:06.845558     300 kubelet.go:267] "Adding static pod path" path="/etc/kubernetes/manifests"
Sep 20 04:56:06 kind-worker2 kubelet[300]: I0920 04:56:06.845640     300 kubelet.go:278] "Adding apiserver pod source"
Sep 20 04:56:06 kind-worker2 kubelet[300]: I0920 04:56:06.845727     300 apiserver.go:42] "Waiting for node sync before watching apiserver pods"
Sep 20 04:56:06 kind-worker2 kubelet[300]: I0920 04:56:06.847163     300 kuberuntime_manager.go:239] "Container runtime initialized" containerRuntime="containerd" version="v1.6.9" apiVersion="v1"
Sep 20 04:56:06 kind-worker2 kubelet[300]: W0920 04:56:06.847805     300 probe.go:268] Flexvolume plugin directory at /usr/libexec/kubernetes/kubelet-plugins/volume/exec/ does not exist. Recreating.
Sep 20 04:56:06 kind-worker2 kubelet[300]: I0920 04:56:06.857430     300 server.go:1181] "Started kubelet"
Sep 20 04:56:06 kind-worker2 kubelet[300]: I0920 04:56:06.858619     300 server.go:150] "Starting to listen" address="0.0.0.0" port=10250
Sep 20 04:56:06 kind-worker2 kubelet[300]: I0920 04:56:06.860913     300 server.go:410] "Adding debug handlers to kubelet server"
Sep 20 04:56:06 kind-worker2 kubelet[300]: I0920 04:56:06.864675     300 fs_resource_analyzer.go:67] "Starting FS ResourceAnalyzer"
Sep 20 04:56:06 kind-worker2 kubelet[300]: I0920 04:56:06.865344     300 volume_manager.go:289] "Starting Kubelet Volume Manager"
Sep 20 04:56:06 kind-worker2 kubelet[300]: I0920 04:56:06.866399     300 desired_state_of_world_populator.go:145] "Desired state populator starts to run"
Sep 20 04:56:06 kind-worker2 kubelet[300]: W0920 04:56:06.866860     300 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.Service: services is forbidden: User "system:anonymous" cannot list resource "services" in API group "" at the cluster scope
Sep 20 04:56:06 kind-worker2 kubelet[300]: E0920 04:56:06.867078     300 reflector.go:138] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Service: failed to list *v1.Service: services is forbidden: User "system:anonymous" cannot list resource "services" in API group "" at the cluster scope
Sep 20 04:56:06 kind-worker2 kubelet[300]: E0920 04:56:06.867194     300 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker2.1786827935d44837", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker2", UID:"kind-worker2", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"Starting", Message:"Starting kubelet.", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker2"}, FirstTimestamp:time.Date(2023, time.September, 20, 4, 56, 6, 857328695, time.Local), LastTimestamp:time.Date(2023, time.September, 20, 4, 56, 6, 857328695, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events is forbidden: User "system:anonymous" cannot create resource "events" in API group "" in the namespace "default"' (will not retry!)
Sep 20 04:56:06 kind-worker2 kubelet[300]: W0920 04:56:06.867679     300 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io is forbidden: User "system:anonymous" cannot list resource "csidrivers" in API group "storage.k8s.io" at the cluster scope
Sep 20 04:56:06 kind-worker2 kubelet[300]: E0920 04:56:06.867721     300 reflector.go:138] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io is forbidden: User "system:anonymous" cannot list resource "csidrivers" in API group "storage.k8s.io" at the cluster scope
Sep 20 04:56:06 kind-worker2 kubelet[300]: W0920 04:56:06.868652     300 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.Node: nodes "kind-worker2" is forbidden: User "system:anonymous" cannot list resource "nodes" in API group "" at the cluster scope
Sep 20 04:56:06 kind-worker2 kubelet[300]: E0920 04:56:06.869053     300 reflector.go:138] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Node: failed to list *v1.Node: nodes "kind-worker2" is forbidden: User "system:anonymous" cannot list resource "nodes" in API group "" at the cluster scope
Sep 20 04:56:06 kind-worker2 kubelet[300]: E0920 04:56:06.869188     300 controller.go:144] failed to ensure lease exists, will retry in 200ms, error: leases.coordination.k8s.io "kind-worker2" is forbidden: User "system:anonymous" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-node-lease"
Sep 20 04:56:06 kind-worker2 kubelet[300]: E0920 04:56:06.869055     300 kubelet.go:2349] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
Sep 20 04:56:06 kind-worker2 kubelet[300]: E0920 04:56:06.974518     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:06 kind-worker2 kubelet[300]: I0920 04:56:06.974797     300 kubelet_node_status.go:70] "Attempting to register node" node="kind-worker2"
Sep 20 04:56:06 kind-worker2 kubelet[300]: I0920 04:56:06.976817     300 cpu_manager.go:213] "Starting CPU manager" policy="none"
Sep 20 04:56:06 kind-worker2 kubelet[300]: I0920 04:56:06.976858     300 cpu_manager.go:214] "Reconciling" reconcilePeriod="10s"
Sep 20 04:56:06 kind-worker2 kubelet[300]: I0920 04:56:06.976895     300 state_mem.go:36] "Initialized new in-memory state store"
Sep 20 04:56:06 kind-worker2 kubelet[300]: E0920 04:56:06.978157     300 kubelet_node_status.go:92] "Unable to register node with API server" err="nodes is forbidden: User \"system:anonymous\" cannot create resource \"nodes\" in API group \"\" at the cluster scope" node="kind-worker2"
Sep 20 04:56:06 kind-worker2 kubelet[300]: E0920 04:56:06.978166     300 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker2.178682793cd2a31b", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker2", UID:"kind-worker2", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientMemory", Message:"Node kind-worker2 status is now: NodeHasSufficientMemory", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker2"}, FirstTimestamp:time.Date(2023, time.September, 20, 4, 56, 6, 974661403, time.Local), LastTimestamp:time.Date(2023, time.September, 20, 4, 56, 6, 974661403, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events is forbidden: User "system:anonymous" cannot create resource "events" in API group "" in the namespace "default"' (will not retry!)
Sep 20 04:56:06 kind-worker2 kubelet[300]: E0920 04:56:06.980446     300 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker2.178682793cd33189", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker2", UID:"kind-worker2", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasNoDiskPressure", Message:"Node kind-worker2 status is now: NodeHasNoDiskPressure", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker2"}, FirstTimestamp:time.Date(2023, time.September, 20, 4, 56, 6, 974697865, time.Local), LastTimestamp:time.Date(2023, time.September, 20, 4, 56, 6, 974697865, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events is forbidden: User "system:anonymous" cannot create resource "events" in API group "" in the namespace "default"' (will not retry!)
Sep 20 04:56:06 kind-worker2 kubelet[300]: E0920 04:56:06.983174     300 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker2.178682793cd35ab6", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker2", UID:"kind-worker2", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientPID", Message:"Node kind-worker2 status is now: NodeHasSufficientPID", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker2"}, FirstTimestamp:time.Date(2023, time.September, 20, 4, 56, 6, 974708406, time.Local), LastTimestamp:time.Date(2023, time.September, 20, 4, 56, 6, 974708406, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events is forbidden: User "system:anonymous" cannot create resource "events" in API group "" in the namespace "default"' (will not retry!)
Sep 20 04:56:06 kind-worker2 kubelet[300]: E0920 04:56:06.987933     300 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker2.178682793cd2a31b", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker2", UID:"kind-worker2", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientMemory", Message:"Node kind-worker2 status is now: NodeHasSufficientMemory", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker2"}, FirstTimestamp:time.Date(2023, time.September, 20, 4, 56, 6, 974661403, time.Local), LastTimestamp:time.Date(2023, time.September, 20, 4, 56, 6, 975260253, time.Local), Count:2, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker2.178682793cd2a31b" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Sep 20 04:56:06 kind-worker2 kubelet[300]: E0920 04:56:06.990558     300 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker2.178682793cd33189", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker2", UID:"kind-worker2", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasNoDiskPressure", Message:"Node kind-worker2 status is now: NodeHasNoDiskPressure", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker2"}, FirstTimestamp:time.Date(2023, time.September, 20, 4, 56, 6, 974697865, time.Local), LastTimestamp:time.Date(2023, time.September, 20, 4, 56, 6, 975271465, time.Local), Count:2, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker2.178682793cd33189" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Sep 20 04:56:06 kind-worker2 kubelet[300]: E0920 04:56:06.992668     300 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker2.178682793cd35ab6", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker2", UID:"kind-worker2", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientPID", Message:"Node kind-worker2 status is now: NodeHasSufficientPID", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker2"}, FirstTimestamp:time.Date(2023, time.September, 20, 4, 56, 6, 974708406, time.Local), LastTimestamp:time.Date(2023, time.September, 20, 4, 56, 6, 975278307, time.Local), Count:2, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker2.178682793cd35ab6" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Sep 20 04:56:07 kind-worker2 kubelet[300]: E0920 04:56:07.072682     300 controller.go:144] failed to ensure lease exists, will retry in 400ms, error: leases.coordination.k8s.io "kind-worker2" is forbidden: User "system:anonymous" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-node-lease"
Sep 20 04:56:07 kind-worker2 kubelet[300]: E0920 04:56:07.075186     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:07 kind-worker2 kubelet[300]: I0920 04:56:07.142053     300 kubelet_network_linux.go:76] "Initialized protocol iptables rules." protocol=IPv4
Sep 20 04:56:07 kind-worker2 kubelet[300]: I0920 04:56:07.156649     300 policy_none.go:49] "None policy: Start"
Sep 20 04:56:07 kind-worker2 kubelet[300]: I0920 04:56:07.160189     300 memory_manager.go:168] "Starting memorymanager" policy="None"
Sep 20 04:56:07 kind-worker2 kubelet[300]: I0920 04:56:07.160303     300 state_mem.go:35] "Initializing new in-memory state store"
Sep 20 04:56:07 kind-worker2 kubelet[300]: E0920 04:56:07.176307     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:07 kind-worker2 kubelet[300]: I0920 04:56:07.181130     300 kubelet_node_status.go:70] "Attempting to register node" node="kind-worker2"
Sep 20 04:56:07 kind-worker2 kubelet[300]: E0920 04:56:07.185006     300 kubelet_node_status.go:92] "Unable to register node with API server" err="nodes is forbidden: User \"system:anonymous\" cannot create resource \"nodes\" in API group \"\" at the cluster scope" node="kind-worker2"
Sep 20 04:56:07 kind-worker2 kubelet[300]: E0920 04:56:07.185357     300 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker2.178682793cd2a31b", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker2", UID:"kind-worker2", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientMemory", Message:"Node kind-worker2 status is now: NodeHasSufficientMemory", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker2"}, FirstTimestamp:time.Date(2023, time.September, 20, 4, 56, 6, 974661403, time.Local), LastTimestamp:time.Date(2023, time.September, 20, 4, 56, 7, 180839022, time.Local), Count:3, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker2.178682793cd2a31b" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Sep 20 04:56:07 kind-worker2 kubelet[300]: E0920 04:56:07.189424     300 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker2.178682793cd33189", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker2", UID:"kind-worker2", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasNoDiskPressure", Message:"Node kind-worker2 status is now: NodeHasNoDiskPressure", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker2"}, FirstTimestamp:time.Date(2023, time.September, 20, 4, 56, 6, 974697865, time.Local), LastTimestamp:time.Date(2023, time.September, 20, 4, 56, 7, 180853026, time.Local), Count:3, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker2.178682793cd33189" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Sep 20 04:56:07 kind-worker2 kubelet[300]: E0920 04:56:07.192290     300 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker2.178682793cd35ab6", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker2", UID:"kind-worker2", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientPID", Message:"Node kind-worker2 status is now: NodeHasSufficientPID", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker2"}, FirstTimestamp:time.Date(2023, time.September, 20, 4, 56, 6, 974708406, time.Local), LastTimestamp:time.Date(2023, time.September, 20, 4, 56, 7, 180860254, time.Local), Count:3, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker2.178682793cd35ab6" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Sep 20 04:56:07 kind-worker2 kubelet[300]: E0920 04:56:07.277950     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:07 kind-worker2 kubelet[300]: W0920 04:56:07.332625     300 watcher.go:93] Error while processing event ("/sys/fs/cgroup/devices/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-besteffort.slice": 0x40000100 == IN_CREATE|IN_ISDIR): inotify_add_watch /sys/fs/cgroup/devices/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-besteffort.slice: no such file or directory
Sep 20 04:56:07 kind-worker2 kubelet[300]: I0920 04:56:07.333867     300 manager.go:610] "Failed to read data from checkpoint" checkpoint="kubelet_internal_checkpoint" err="checkpoint is not found"
Sep 20 04:56:07 kind-worker2 kubelet[300]: I0920 04:56:07.334489     300 plugin_manager.go:114] "Starting Kubelet Plugin Manager"
Sep 20 04:56:07 kind-worker2 kubelet[300]: E0920 04:56:07.338231     300 eviction_manager.go:254] "Eviction manager: failed to get summary stats" err="failed to get node info: node \"kind-worker2\" not found"
Sep 20 04:56:07 kind-worker2 kubelet[300]: E0920 04:56:07.347007     300 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker2.1786827952baaae5", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker2", UID:"kind-worker2", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeAllocatableEnforced", Message:"Updated Node Allocatable limit across pods", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker2"}, FirstTimestamp:time.Date(2023, time.September, 20, 4, 56, 7, 342189285, time.Local), LastTimestamp:time.Date(2023, time.September, 20, 4, 56, 7, 342189285, time.Local), Count:1, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events is forbidden: User "system:anonymous" cannot create resource "events" in API group "" in the namespace "default"' (will not retry!)
Sep 20 04:56:07 kind-worker2 kubelet[300]: E0920 04:56:07.378574     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:07 kind-worker2 kubelet[300]: E0920 04:56:07.475690     300 controller.go:144] failed to ensure lease exists, will retry in 800ms, error: leases.coordination.k8s.io "kind-worker2" is forbidden: User "system:anonymous" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-node-lease"
Sep 20 04:56:07 kind-worker2 kubelet[300]: E0920 04:56:07.479710     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:07 kind-worker2 kubelet[300]: E0920 04:56:07.580860     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:07 kind-worker2 kubelet[300]: I0920 04:56:07.588245     300 kubelet_node_status.go:70] "Attempting to register node" node="kind-worker2"
Sep 20 04:56:07 kind-worker2 kubelet[300]: E0920 04:56:07.591849     300 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker2.178682793cd2a31b", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker2", UID:"kind-worker2", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientMemory", Message:"Node kind-worker2 status is now: NodeHasSufficientMemory", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker2"}, FirstTimestamp:time.Date(2023, time.September, 20, 4, 56, 6, 974661403, time.Local), LastTimestamp:time.Date(2023, time.September, 20, 4, 56, 7, 588037435, time.Local), Count:4, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker2.178682793cd2a31b" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Sep 20 04:56:07 kind-worker2 kubelet[300]: E0920 04:56:07.592025     300 kubelet_node_status.go:92] "Unable to register node with API server" err="nodes is forbidden: User \"system:anonymous\" cannot create resource \"nodes\" in API group \"\" at the cluster scope" node="kind-worker2"
Sep 20 04:56:07 kind-worker2 kubelet[300]: E0920 04:56:07.594022     300 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker2.178682793cd33189", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker2", UID:"kind-worker2", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasNoDiskPressure", Message:"Node kind-worker2 status is now: NodeHasNoDiskPressure", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker2"}, FirstTimestamp:time.Date(2023, time.September, 20, 4, 56, 6, 974697865, time.Local), LastTimestamp:time.Date(2023, time.September, 20, 4, 56, 7, 588089286, time.Local), Count:4, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker2.178682793cd33189" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Sep 20 04:56:07 kind-worker2 kubelet[300]: E0920 04:56:07.661020     300 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker2.178682793cd35ab6", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker2", UID:"kind-worker2", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientPID", Message:"Node kind-worker2 status is now: NodeHasSufficientPID", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker2"}, FirstTimestamp:time.Date(2023, time.September, 20, 4, 56, 6, 974708406, time.Local), LastTimestamp:time.Date(2023, time.September, 20, 4, 56, 7, 588103786, time.Local), Count:4, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker2.178682793cd35ab6" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Sep 20 04:56:07 kind-worker2 kubelet[300]: E0920 04:56:07.681932     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:07 kind-worker2 kubelet[300]: I0920 04:56:07.725818     300 kubelet_network_linux.go:76] "Initialized protocol iptables rules." protocol=IPv6
Sep 20 04:56:07 kind-worker2 kubelet[300]: I0920 04:56:07.725951     300 status_manager.go:161] "Starting to sync pod status with apiserver"
Sep 20 04:56:07 kind-worker2 kubelet[300]: I0920 04:56:07.726027     300 kubelet.go:1986] "Starting kubelet main sync loop"
Sep 20 04:56:07 kind-worker2 kubelet[300]: E0920 04:56:07.726267     300 kubelet.go:2010] "Skipping pod synchronization" err="PLEG is not healthy: pleg has yet to be successful"
Sep 20 04:56:07 kind-worker2 kubelet[300]: W0920 04:56:07.730195     300 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.RuntimeClass: runtimeclasses.node.k8s.io is forbidden: User "system:anonymous" cannot list resource "runtimeclasses" in API group "node.k8s.io" at the cluster scope
Sep 20 04:56:07 kind-worker2 kubelet[300]: E0920 04:56:07.730583     300 reflector.go:138] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.RuntimeClass: failed to list *v1.RuntimeClass: runtimeclasses.node.k8s.io is forbidden: User "system:anonymous" cannot list resource "runtimeclasses" in API group "node.k8s.io" at the cluster scope
Sep 20 04:56:07 kind-worker2 kubelet[300]: W0920 04:56:07.780651     300 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.Service: services is forbidden: User "system:anonymous" cannot list resource "services" in API group "" at the cluster scope
Sep 20 04:56:07 kind-worker2 kubelet[300]: E0920 04:56:07.780746     300 reflector.go:138] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Service: failed to list *v1.Service: services is forbidden: User "system:anonymous" cannot list resource "services" in API group "" at the cluster scope
Sep 20 04:56:07 kind-worker2 kubelet[300]: E0920 04:56:07.782808     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:07 kind-worker2 kubelet[300]: W0920 04:56:07.854344     300 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.Node: nodes "kind-worker2" is forbidden: User "system:anonymous" cannot list resource "nodes" in API group "" at the cluster scope
Sep 20 04:56:07 kind-worker2 kubelet[300]: E0920 04:56:07.854550     300 reflector.go:138] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Node: failed to list *v1.Node: nodes "kind-worker2" is forbidden: User "system:anonymous" cannot list resource "nodes" in API group "" at the cluster scope
Sep 20 04:56:07 kind-worker2 kubelet[300]: E0920 04:56:07.883545     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:07 kind-worker2 kubelet[300]: E0920 04:56:07.984650     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:08 kind-worker2 kubelet[300]: W0920 04:56:08.025322     300 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io is forbidden: User "system:anonymous" cannot list resource "csidrivers" in API group "storage.k8s.io" at the cluster scope
Sep 20 04:56:08 kind-worker2 kubelet[300]: E0920 04:56:08.025485     300 reflector.go:138] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io is forbidden: User "system:anonymous" cannot list resource "csidrivers" in API group "storage.k8s.io" at the cluster scope
Sep 20 04:56:08 kind-worker2 kubelet[300]: E0920 04:56:08.085226     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:08 kind-worker2 kubelet[300]: E0920 04:56:08.185818     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:08 kind-worker2 kubelet[300]: E0920 04:56:08.279991     300 controller.go:144] failed to ensure lease exists, will retry in 1.6s, error: leases.coordination.k8s.io "kind-worker2" is forbidden: User "system:anonymous" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-node-lease"
Sep 20 04:56:08 kind-worker2 kubelet[300]: E0920 04:56:08.286283     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:08 kind-worker2 kubelet[300]: E0920 04:56:08.386699     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:08 kind-worker2 kubelet[300]: I0920 04:56:08.397605     300 kubelet_node_status.go:70] "Attempting to register node" node="kind-worker2"
Sep 20 04:56:08 kind-worker2 kubelet[300]: E0920 04:56:08.401366     300 kubelet_node_status.go:92] "Unable to register node with API server" err="nodes is forbidden: User \"system:anonymous\" cannot create resource \"nodes\" in API group \"\" at the cluster scope" node="kind-worker2"
Sep 20 04:56:08 kind-worker2 kubelet[300]: E0920 04:56:08.401450     300 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker2.178682793cd2a31b", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker2", UID:"kind-worker2", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientMemory", Message:"Node kind-worker2 status is now: NodeHasSufficientMemory", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker2"}, FirstTimestamp:time.Date(2023, time.September, 20, 4, 56, 6, 974661403, time.Local), LastTimestamp:time.Date(2023, time.September, 20, 4, 56, 8, 397486414, time.Local), Count:5, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker2.178682793cd2a31b" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Sep 20 04:56:08 kind-worker2 kubelet[300]: E0920 04:56:08.403693     300 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker2.178682793cd33189", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker2", UID:"kind-worker2", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasNoDiskPressure", Message:"Node kind-worker2 status is now: NodeHasNoDiskPressure", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker2"}, FirstTimestamp:time.Date(2023, time.September, 20, 4, 56, 6, 974697865, time.Local), LastTimestamp:time.Date(2023, time.September, 20, 4, 56, 8, 397530102, time.Local), Count:5, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker2.178682793cd33189" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Sep 20 04:56:08 kind-worker2 kubelet[300]: E0920 04:56:08.405554     300 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker2.178682793cd35ab6", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker2", UID:"kind-worker2", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientPID", Message:"Node kind-worker2 status is now: NodeHasSufficientPID", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker2"}, FirstTimestamp:time.Date(2023, time.September, 20, 4, 56, 6, 974708406, time.Local), LastTimestamp:time.Date(2023, time.September, 20, 4, 56, 8, 397539016, time.Local), Count:5, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker2.178682793cd35ab6" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Sep 20 04:56:08 kind-worker2 kubelet[300]: E0920 04:56:08.487435     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:08 kind-worker2 kubelet[300]: E0920 04:56:08.588401     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:08 kind-worker2 kubelet[300]: E0920 04:56:08.689315     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:08 kind-worker2 kubelet[300]: E0920 04:56:08.789703     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:08 kind-worker2 kubelet[300]: E0920 04:56:08.890736     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:08 kind-worker2 kubelet[300]: E0920 04:56:08.991947     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:09 kind-worker2 kubelet[300]: W0920 04:56:09.004273     300 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.RuntimeClass: runtimeclasses.node.k8s.io is forbidden: User "system:anonymous" cannot list resource "runtimeclasses" in API group "node.k8s.io" at the cluster scope
Sep 20 04:56:09 kind-worker2 kubelet[300]: E0920 04:56:09.004363     300 reflector.go:138] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.RuntimeClass: failed to list *v1.RuntimeClass: runtimeclasses.node.k8s.io is forbidden: User "system:anonymous" cannot list resource "runtimeclasses" in API group "node.k8s.io" at the cluster scope
Sep 20 04:56:09 kind-worker2 kubelet[300]: E0920 04:56:09.093007     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:09 kind-worker2 kubelet[300]: E0920 04:56:09.194177     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:09 kind-worker2 kubelet[300]: E0920 04:56:09.294657     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:09 kind-worker2 kubelet[300]: E0920 04:56:09.395207     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:09 kind-worker2 kubelet[300]: E0920 04:56:09.496257     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:09 kind-worker2 kubelet[300]: E0920 04:56:09.597119     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:09 kind-worker2 kubelet[300]: E0920 04:56:09.697984     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:09 kind-worker2 kubelet[300]: E0920 04:56:09.798295     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:09 kind-worker2 kubelet[300]: E0920 04:56:09.882757     300 controller.go:144] failed to ensure lease exists, will retry in 3.2s, error: leases.coordination.k8s.io "kind-worker2" is forbidden: User "system:anonymous" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-node-lease"
Sep 20 04:56:09 kind-worker2 kubelet[300]: E0920 04:56:09.899188     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:10 kind-worker2 kubelet[300]: E0920 04:56:10.000189     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:10 kind-worker2 kubelet[300]: I0920 04:56:10.003932     300 kubelet_node_status.go:70] "Attempting to register node" node="kind-worker2"
Sep 20 04:56:10 kind-worker2 kubelet[300]: E0920 04:56:10.006670     300 kubelet_node_status.go:92] "Unable to register node with API server" err="nodes is forbidden: User \"system:anonymous\" cannot create resource \"nodes\" in API group \"\" at the cluster scope" node="kind-worker2"
Sep 20 04:56:10 kind-worker2 kubelet[300]: E0920 04:56:10.007244     300 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker2.178682793cd2a31b", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker2", UID:"kind-worker2", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientMemory", Message:"Node kind-worker2 status is now: NodeHasSufficientMemory", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker2"}, FirstTimestamp:time.Date(2023, time.September, 20, 4, 56, 6, 974661403, time.Local), LastTimestamp:time.Date(2023, time.September, 20, 4, 56, 10, 3849977, time.Local), Count:6, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker2.178682793cd2a31b" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Sep 20 04:56:10 kind-worker2 kubelet[300]: E0920 04:56:10.009527     300 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker2.178682793cd33189", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker2", UID:"kind-worker2", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasNoDiskPressure", Message:"Node kind-worker2 status is now: NodeHasNoDiskPressure", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker2"}, FirstTimestamp:time.Date(2023, time.September, 20, 4, 56, 6, 974697865, time.Local), LastTimestamp:time.Date(2023, time.September, 20, 4, 56, 10, 3879171, time.Local), Count:6, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker2.178682793cd33189" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Sep 20 04:56:10 kind-worker2 kubelet[300]: E0920 04:56:10.011458     300 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker2.178682793cd35ab6", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker2", UID:"kind-worker2", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientPID", Message:"Node kind-worker2 status is now: NodeHasSufficientPID", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker2"}, FirstTimestamp:time.Date(2023, time.September, 20, 4, 56, 6, 974708406, time.Local), LastTimestamp:time.Date(2023, time.September, 20, 4, 56, 10, 3887462, time.Local), Count:6, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker2.178682793cd35ab6" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Sep 20 04:56:10 kind-worker2 kubelet[300]: E0920 04:56:10.101335     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:10 kind-worker2 kubelet[300]: E0920 04:56:10.202311     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:10 kind-worker2 kubelet[300]: E0920 04:56:10.303543     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:10 kind-worker2 kubelet[300]: E0920 04:56:10.403815     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:10 kind-worker2 kubelet[300]: W0920 04:56:10.430742     300 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.Node: nodes "kind-worker2" is forbidden: User "system:anonymous" cannot list resource "nodes" in API group "" at the cluster scope
Sep 20 04:56:10 kind-worker2 kubelet[300]: E0920 04:56:10.430814     300 reflector.go:138] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Node: failed to list *v1.Node: nodes "kind-worker2" is forbidden: User "system:anonymous" cannot list resource "nodes" in API group "" at the cluster scope
Sep 20 04:56:10 kind-worker2 kubelet[300]: E0920 04:56:10.504400     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:10 kind-worker2 kubelet[300]: E0920 04:56:10.605615     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:10 kind-worker2 kubelet[300]: W0920 04:56:10.609445     300 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.Service: services is forbidden: User "system:anonymous" cannot list resource "services" in API group "" at the cluster scope
Sep 20 04:56:10 kind-worker2 kubelet[300]: E0920 04:56:10.609528     300 reflector.go:138] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Service: failed to list *v1.Service: services is forbidden: User "system:anonymous" cannot list resource "services" in API group "" at the cluster scope
Sep 20 04:56:10 kind-worker2 kubelet[300]: E0920 04:56:10.706276     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:10 kind-worker2 kubelet[300]: E0920 04:56:10.807251     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:10 kind-worker2 kubelet[300]: E0920 04:56:10.908415     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:11 kind-worker2 kubelet[300]: E0920 04:56:11.008666     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:11 kind-worker2 kubelet[300]: E0920 04:56:11.109919     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:11 kind-worker2 kubelet[300]: W0920 04:56:11.208802     300 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io is forbidden: User "system:anonymous" cannot list resource "csidrivers" in API group "storage.k8s.io" at the cluster scope
Sep 20 04:56:11 kind-worker2 kubelet[300]: E0920 04:56:11.208865     300 reflector.go:138] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io is forbidden: User "system:anonymous" cannot list resource "csidrivers" in API group "storage.k8s.io" at the cluster scope
Sep 20 04:56:11 kind-worker2 kubelet[300]: E0920 04:56:11.210923     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:11 kind-worker2 kubelet[300]: E0920 04:56:11.312008     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:11 kind-worker2 kubelet[300]: E0920 04:56:11.413052     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:11 kind-worker2 kubelet[300]: E0920 04:56:11.514118     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:11 kind-worker2 kubelet[300]: E0920 04:56:11.615157     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:11 kind-worker2 kubelet[300]: E0920 04:56:11.716170     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:11 kind-worker2 kubelet[300]: W0920 04:56:11.761974     300 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.RuntimeClass: runtimeclasses.node.k8s.io is forbidden: User "system:anonymous" cannot list resource "runtimeclasses" in API group "node.k8s.io" at the cluster scope
Sep 20 04:56:11 kind-worker2 kubelet[300]: E0920 04:56:11.762046     300 reflector.go:138] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.RuntimeClass: failed to list *v1.RuntimeClass: runtimeclasses.node.k8s.io is forbidden: User "system:anonymous" cannot list resource "runtimeclasses" in API group "node.k8s.io" at the cluster scope
Sep 20 04:56:11 kind-worker2 kubelet[300]: E0920 04:56:11.817021     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:11 kind-worker2 kubelet[300]: E0920 04:56:11.917692     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:12 kind-worker2 kubelet[300]: E0920 04:56:12.018194     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:12 kind-worker2 kubelet[300]: E0920 04:56:12.119145     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:12 kind-worker2 kubelet[300]: E0920 04:56:12.220117     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:12 kind-worker2 kubelet[300]: E0920 04:56:12.320302     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:12 kind-worker2 kubelet[300]: E0920 04:56:12.335411     300 kubelet.go:2349] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
Sep 20 04:56:12 kind-worker2 kubelet[300]: E0920 04:56:12.420532     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:12 kind-worker2 kubelet[300]: E0920 04:56:12.521403     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:12 kind-worker2 kubelet[300]: E0920 04:56:12.622439     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:12 kind-worker2 kubelet[300]: E0920 04:56:12.723280     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:12 kind-worker2 kubelet[300]: E0920 04:56:12.823745     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:12 kind-worker2 kubelet[300]: E0920 04:56:12.924897     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:13 kind-worker2 kubelet[300]: E0920 04:56:13.025810     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:13 kind-worker2 kubelet[300]: E0920 04:56:13.087408     300 controller.go:144] failed to ensure lease exists, will retry in 6.4s, error: leases.coordination.k8s.io "kind-worker2" is forbidden: User "system:anonymous" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "kube-node-lease"
Sep 20 04:56:13 kind-worker2 kubelet[300]: E0920 04:56:13.127050     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:13 kind-worker2 kubelet[300]: I0920 04:56:13.209495     300 kubelet_node_status.go:70] "Attempting to register node" node="kind-worker2"
Sep 20 04:56:13 kind-worker2 kubelet[300]: E0920 04:56:13.213689     300 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker2.178682793cd2a31b", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker2", UID:"kind-worker2", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientMemory", Message:"Node kind-worker2 status is now: NodeHasSufficientMemory", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker2"}, FirstTimestamp:time.Date(2023, time.September, 20, 4, 56, 6, 974661403, time.Local), LastTimestamp:time.Date(2023, time.September, 20, 4, 56, 13, 209296556, time.Local), Count:7, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker2.178682793cd2a31b" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Sep 20 04:56:13 kind-worker2 kubelet[300]: E0920 04:56:13.214783     300 kubelet_node_status.go:92] "Unable to register node with API server" err="nodes is forbidden: User \"system:anonymous\" cannot create resource \"nodes\" in API group \"\" at the cluster scope" node="kind-worker2"
Sep 20 04:56:13 kind-worker2 kubelet[300]: E0920 04:56:13.216359     300 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker2.178682793cd33189", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker2", UID:"kind-worker2", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasNoDiskPressure", Message:"Node kind-worker2 status is now: NodeHasNoDiskPressure", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker2"}, FirstTimestamp:time.Date(2023, time.September, 20, 4, 56, 6, 974697865, time.Local), LastTimestamp:time.Date(2023, time.September, 20, 4, 56, 13, 209334193, time.Local), Count:7, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker2.178682793cd33189" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Sep 20 04:56:13 kind-worker2 kubelet[300]: E0920 04:56:13.219006     300 event.go:267] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kind-worker2.178682793cd35ab6", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ZZZ_DeprecatedClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"kind-worker2", UID:"kind-worker2", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientPID", Message:"Node kind-worker2 status is now: NodeHasSufficientPID", Source:v1.EventSource{Component:"kubelet", Host:"kind-worker2"}, FirstTimestamp:time.Date(2023, time.September, 20, 4, 56, 6, 974708406, time.Local), LastTimestamp:time.Date(2023, time.September, 20, 4, 56, 13, 209343095, time.Local), Count:7, Type:"Normal", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "kind-worker2.178682793cd35ab6" is forbidden: User "system:anonymous" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
Sep 20 04:56:13 kind-worker2 kubelet[300]: E0920 04:56:13.228159     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:13 kind-worker2 kubelet[300]: E0920 04:56:13.328340     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:13 kind-worker2 kubelet[300]: E0920 04:56:13.429602     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:13 kind-worker2 kubelet[300]: E0920 04:56:13.530661     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:13 kind-worker2 kubelet[300]: E0920 04:56:13.631649     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:13 kind-worker2 kubelet[300]: E0920 04:56:13.732721     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:13 kind-worker2 kubelet[300]: E0920 04:56:13.833347     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:13 kind-worker2 kubelet[300]: E0920 04:56:13.934248     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:14 kind-worker2 kubelet[300]: E0920 04:56:14.034894     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:14 kind-worker2 kubelet[300]: E0920 04:56:14.135639     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:14 kind-worker2 kubelet[300]: E0920 04:56:14.236624     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:14 kind-worker2 kubelet[300]: E0920 04:56:14.336925     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:14 kind-worker2 kubelet[300]: E0920 04:56:14.437670     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:14 kind-worker2 kubelet[300]: E0920 04:56:14.538882     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:14 kind-worker2 kubelet[300]: E0920 04:56:14.640125     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:14 kind-worker2 kubelet[300]: E0920 04:56:14.743722     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:14 kind-worker2 kubelet[300]: E0920 04:56:14.852541     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:14 kind-worker2 kubelet[300]: E0920 04:56:14.952754     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:15 kind-worker2 kubelet[300]: E0920 04:56:15.053832     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:15 kind-worker2 kubelet[300]: E0920 04:56:15.154754     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:15 kind-worker2 kubelet[300]: W0920 04:56:15.236715     300 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.Node: nodes "kind-worker2" is forbidden: User "system:anonymous" cannot list resource "nodes" in API group "" at the cluster scope
Sep 20 04:56:15 kind-worker2 kubelet[300]: E0920 04:56:15.236835     300 reflector.go:138] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Node: failed to list *v1.Node: nodes "kind-worker2" is forbidden: User "system:anonymous" cannot list resource "nodes" in API group "" at the cluster scope
Sep 20 04:56:15 kind-worker2 kubelet[300]: E0920 04:56:15.255707     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:15 kind-worker2 kubelet[300]: E0920 04:56:15.356187     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:15 kind-worker2 kubelet[300]: E0920 04:56:15.457163     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:15 kind-worker2 kubelet[300]: E0920 04:56:15.558239     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:15 kind-worker2 kubelet[300]: W0920 04:56:15.618639     300 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.RuntimeClass: runtimeclasses.node.k8s.io is forbidden: User "system:anonymous" cannot list resource "runtimeclasses" in API group "node.k8s.io" at the cluster scope
Sep 20 04:56:15 kind-worker2 kubelet[300]: E0920 04:56:15.618706     300 reflector.go:138] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.RuntimeClass: failed to list *v1.RuntimeClass: runtimeclasses.node.k8s.io is forbidden: User "system:anonymous" cannot list resource "runtimeclasses" in API group "node.k8s.io" at the cluster scope
Sep 20 04:56:15 kind-worker2 kubelet[300]: E0920 04:56:15.658981     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:15 kind-worker2 kubelet[300]: E0920 04:56:15.759888     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:15 kind-worker2 kubelet[300]: W0920 04:56:15.813347     300 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.Service: services is forbidden: User "system:anonymous" cannot list resource "services" in API group "" at the cluster scope
Sep 20 04:56:15 kind-worker2 kubelet[300]: E0920 04:56:15.813436     300 reflector.go:138] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Service: failed to list *v1.Service: services is forbidden: User "system:anonymous" cannot list resource "services" in API group "" at the cluster scope
Sep 20 04:56:15 kind-worker2 kubelet[300]: E0920 04:56:15.861167     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:15 kind-worker2 kubelet[300]: E0920 04:56:15.961890     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:16 kind-worker2 kubelet[300]: E0920 04:56:16.062921     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:16 kind-worker2 kubelet[300]: E0920 04:56:16.163991     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:16 kind-worker2 kubelet[300]: E0920 04:56:16.265185     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:16 kind-worker2 kubelet[300]: E0920 04:56:16.366340     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:16 kind-worker2 kubelet[300]: E0920 04:56:16.467359     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:16 kind-worker2 kubelet[300]: W0920 04:56:16.562543     300 reflector.go:324] vendor/k8s.io/client-go/informers/factory.go:134: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io is forbidden: User "system:anonymous" cannot list resource "csidrivers" in API group "storage.k8s.io" at the cluster scope
Sep 20 04:56:16 kind-worker2 kubelet[300]: E0920 04:56:16.562616     300 reflector.go:138] vendor/k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: csidrivers.storage.k8s.io is forbidden: User "system:anonymous" cannot list resource "csidrivers" in API group "storage.k8s.io" at the cluster scope
Sep 20 04:56:16 kind-worker2 kubelet[300]: E0920 04:56:16.567875     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:16 kind-worker2 kubelet[300]: E0920 04:56:16.668757     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:16 kind-worker2 kubelet[300]: E0920 04:56:16.769449     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:16 kind-worker2 kubelet[300]: I0920 04:56:16.774769     300 transport.go:135] "Certificate rotation detected, shutting down client connections to start using new credentials"
Sep 20 04:56:16 kind-worker2 kubelet[300]: E0920 04:56:16.869609     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:16 kind-worker2 kubelet[300]: E0920 04:56:16.970313     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:17 kind-worker2 kubelet[300]: E0920 04:56:17.071432     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:17 kind-worker2 kubelet[300]: E0920 04:56:17.172110     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:17 kind-worker2 kubelet[300]: E0920 04:56:17.272654     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:17 kind-worker2 kubelet[300]: E0920 04:56:17.337730     300 kubelet.go:2349] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
Sep 20 04:56:17 kind-worker2 kubelet[300]: E0920 04:56:17.338400     300 eviction_manager.go:254] "Eviction manager: failed to get summary stats" err="failed to get node info: node \"kind-worker2\" not found"
Sep 20 04:56:17 kind-worker2 kubelet[300]: E0920 04:56:17.373841     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:17 kind-worker2 kubelet[300]: E0920 04:56:17.474821     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:17 kind-worker2 kubelet[300]: E0920 04:56:17.509997     300 csi_plugin.go:297] Failed to initialize CSINode: error updating CSINode annotation: timed out waiting for the condition; caused by: nodes "kind-worker2" not found
Sep 20 04:56:17 kind-worker2 kubelet[300]: E0920 04:56:17.575437     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:17 kind-worker2 kubelet[300]: E0920 04:56:17.676324     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:17 kind-worker2 kubelet[300]: E0920 04:56:17.777145     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:17 kind-worker2 kubelet[300]: E0920 04:56:17.877976     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:17 kind-worker2 kubelet[300]: E0920 04:56:17.979156     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:18 kind-worker2 kubelet[300]: E0920 04:56:18.079903     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:18 kind-worker2 kubelet[300]: E0920 04:56:18.180627     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:18 kind-worker2 kubelet[300]: E0920 04:56:18.271422     300 csi_plugin.go:297] Failed to initialize CSINode: error updating CSINode annotation: timed out waiting for the condition; caused by: nodes "kind-worker2" not found
Sep 20 04:56:18 kind-worker2 kubelet[300]: E0920 04:56:18.281803     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:18 kind-worker2 kubelet[300]: E0920 04:56:18.382303     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:18 kind-worker2 kubelet[300]: E0920 04:56:18.483393     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:18 kind-worker2 kubelet[300]: E0920 04:56:18.583999     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:18 kind-worker2 kubelet[300]: E0920 04:56:18.684870     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:18 kind-worker2 kubelet[300]: E0920 04:56:18.785318     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:18 kind-worker2 kubelet[300]: E0920 04:56:18.885509     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:18 kind-worker2 kubelet[300]: E0920 04:56:18.986446     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:19 kind-worker2 kubelet[300]: E0920 04:56:19.087596     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:19 kind-worker2 kubelet[300]: E0920 04:56:19.187844     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:19 kind-worker2 kubelet[300]: E0920 04:56:19.288496     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:19 kind-worker2 kubelet[300]: E0920 04:56:19.388719     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:19 kind-worker2 kubelet[300]: E0920 04:56:19.489180     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:19 kind-worker2 kubelet[300]: E0920 04:56:19.496963     300 nodelease.go:49] "Failed to get node when trying to set owner ref to the node lease" err="nodes \"kind-worker2\" not found" node="kind-worker2"
Sep 20 04:56:19 kind-worker2 kubelet[300]: E0920 04:56:19.589811     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:19 kind-worker2 kubelet[300]: I0920 04:56:19.616664     300 kubelet_node_status.go:70] "Attempting to register node" node="kind-worker2"
Sep 20 04:56:19 kind-worker2 kubelet[300]: I0920 04:56:19.672779     300 kubelet_node_status.go:73] "Successfully registered node" node="kind-worker2"
Sep 20 04:56:19 kind-worker2 kubelet[300]: E0920 04:56:19.690342     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:19 kind-worker2 kubelet[300]: E0920 04:56:19.790722     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:19 kind-worker2 kubelet[300]: E0920 04:56:19.891770     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:19 kind-worker2 kubelet[300]: E0920 04:56:19.992587     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:20 kind-worker2 kubelet[300]: E0920 04:56:20.093695     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:20 kind-worker2 kubelet[300]: E0920 04:56:20.194692     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:20 kind-worker2 kubelet[300]: E0920 04:56:20.295680     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:20 kind-worker2 kubelet[300]: E0920 04:56:20.396426     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:20 kind-worker2 kubelet[300]: E0920 04:56:20.497337     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:20 kind-worker2 kubelet[300]: E0920 04:56:20.598204     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:20 kind-worker2 kubelet[300]: E0920 04:56:20.699133     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:20 kind-worker2 kubelet[300]: E0920 04:56:20.799296     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:20 kind-worker2 kubelet[300]: E0920 04:56:20.900122     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:21 kind-worker2 kubelet[300]: E0920 04:56:21.001129     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:21 kind-worker2 kubelet[300]: E0920 04:56:21.102142     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:21 kind-worker2 kubelet[300]: E0920 04:56:21.203126     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:21 kind-worker2 kubelet[300]: E0920 04:56:21.304308     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:21 kind-worker2 kubelet[300]: E0920 04:56:21.404692     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:21 kind-worker2 kubelet[300]: E0920 04:56:21.505814     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:21 kind-worker2 kubelet[300]: E0920 04:56:21.606902     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:21 kind-worker2 kubelet[300]: E0920 04:56:21.708030     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:21 kind-worker2 kubelet[300]: E0920 04:56:21.808717     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:21 kind-worker2 kubelet[300]: E0920 04:56:21.909210     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:22 kind-worker2 kubelet[300]: E0920 04:56:22.010175     300 kubelet.go:2424] "Error getting node" err="node \"kind-worker2\" not found"
Sep 20 04:56:22 kind-worker2 kubelet[300]: I0920 04:56:22.110446     300 kuberuntime_manager.go:1095] "Updating runtime config through cri with podcidr" CIDR="10.244.1.0/24"
Sep 20 04:56:22 kind-worker2 kubelet[300]: I0920 04:56:22.112179     300 kubelet_network.go:60] "Updating Pod CIDR" originalPodCIDR="" newPodCIDR="10.244.1.0/24"
Sep 20 04:56:22 kind-worker2 kubelet[300]: E0920 04:56:22.112993     300 kubelet.go:2349] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
Sep 20 04:56:22 kind-worker2 kubelet[300]: E0920 04:56:22.339518     300 kubelet.go:2349] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
Sep 20 04:56:22 kind-worker2 kubelet[300]: I0920 04:56:22.861729     300 apiserver.go:52] "Watching apiserver"
Sep 20 04:56:22 kind-worker2 kubelet[300]: I0920 04:56:22.876309     300 topology_manager.go:200] "Topology Admit Handler"
Sep 20 04:56:22 kind-worker2 kubelet[300]: I0920 04:56:22.876544     300 topology_manager.go:200] "Topology Admit Handler"
Sep 20 04:56:22 kind-worker2 kubelet[300]: E0920 04:56:22.908203     300 watcher.go:152] Failed to watch directory "/sys/fs/cgroup/devices/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-besteffort.slice/kubelet-kubepods-besteffort-podd21054b8_786d_478b_8623_dea1610e417c.slice": readdirent /sys/fs/cgroup/devices/kubelet.slice/kubelet-kubepods.slice/kubelet-kubepods-besteffort.slice/kubelet-kubepods-besteffort-podd21054b8_786d_478b_8623_dea1610e417c.slice: no such file or directory
Sep 20 04:56:22 kind-worker2 kubelet[300]: I0920 04:56:22.988638     300 reconciler.go:342] "operationExecutor.VerifyControllerAttachedVolume started for volume \"cni-cfg\" (UniqueName: \"kubernetes.io/host-path/ddc32845-7997-4180-978f-5e99bc66b471-cni-cfg\") pod \"kindnet-t84s5\" (UID: \"ddc32845-7997-4180-978f-5e99bc66b471\") " pod="kube-system/kindnet-t84s5"
Sep 20 04:56:22 kind-worker2 kubelet[300]: I0920 04:56:22.989036     300 reconciler.go:342] "operationExecutor.VerifyControllerAttachedVolume started for volume \"xtables-lock\" (UniqueName: \"kubernetes.io/host-path/ddc32845-7997-4180-978f-5e99bc66b471-xtables-lock\") pod \"kindnet-t84s5\" (UID: \"ddc32845-7997-4180-978f-5e99bc66b471\") " pod="kube-system/kindnet-t84s5"
Sep 20 04:56:22 kind-worker2 kubelet[300]: I0920 04:56:22.989340     300 reconciler.go:342] "operationExecutor.VerifyControllerAttachedVolume started for volume \"lib-modules\" (UniqueName: \"kubernetes.io/host-path/ddc32845-7997-4180-978f-5e99bc66b471-lib-modules\") pod \"kindnet-t84s5\" (UID: \"ddc32845-7997-4180-978f-5e99bc66b471\") " pod="kube-system/kindnet-t84s5"
Sep 20 04:56:22 kind-worker2 kubelet[300]: I0920 04:56:22.989557     300 reconciler.go:342] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kube-api-access-h4tgt\" (UniqueName: \"kubernetes.io/projected/ddc32845-7997-4180-978f-5e99bc66b471-kube-api-access-h4tgt\") pod \"kindnet-t84s5\" (UID: \"ddc32845-7997-4180-978f-5e99bc66b471\") " pod="kube-system/kindnet-t84s5"
Sep 20 04:56:22 kind-worker2 kubelet[300]: I0920 04:56:22.989820     300 reconciler.go:342] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kube-proxy\" (UniqueName: \"kubernetes.io/configmap/d21054b8-786d-478b-8623-dea1610e417c-kube-proxy\") pod \"kube-proxy-49wc9\" (UID: \"d21054b8-786d-478b-8623-dea1610e417c\") " pod="kube-system/kube-proxy-49wc9"
Sep 20 04:56:22 kind-worker2 kubelet[300]: I0920 04:56:22.990031     300 reconciler.go:342] "operationExecutor.VerifyControllerAttachedVolume started for volume \"xtables-lock\" (UniqueName: \"kubernetes.io/host-path/d21054b8-786d-478b-8623-dea1610e417c-xtables-lock\") pod \"kube-proxy-49wc9\" (UID: \"d21054b8-786d-478b-8623-dea1610e417c\") " pod="kube-system/kube-proxy-49wc9"
Sep 20 04:56:22 kind-worker2 kubelet[300]: I0920 04:56:22.990254     300 reconciler.go:342] "operationExecutor.VerifyControllerAttachedVolume started for volume \"lib-modules\" (UniqueName: \"kubernetes.io/host-path/d21054b8-786d-478b-8623-dea1610e417c-lib-modules\") pod \"kube-proxy-49wc9\" (UID: \"d21054b8-786d-478b-8623-dea1610e417c\") " pod="kube-system/kube-proxy-49wc9"
Sep 20 04:56:22 kind-worker2 kubelet[300]: I0920 04:56:22.990515     300 reconciler.go:342] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kube-api-access-4s65b\" (UniqueName: \"kubernetes.io/projected/d21054b8-786d-478b-8623-dea1610e417c-kube-api-access-4s65b\") pod \"kube-proxy-49wc9\" (UID: \"d21054b8-786d-478b-8623-dea1610e417c\") " pod="kube-system/kube-proxy-49wc9"
Sep 20 04:56:22 kind-worker2 kubelet[300]: I0920 04:56:22.990720     300 reconciler.go:159] "Reconciler: start to sync state"
Sep 20 04:56:25 kind-worker2 kubelet[300]: E0920 04:56:25.898411     300 kuberuntime_manager.go:905] container &Container{Name:kube-proxy,Image:k8s.gcr.io/kube-proxy:v1.24.7,Command:[/usr/local/bin/kube-proxy --config=/var/lib/kube-proxy/config.conf --hostname-override=$(NODE_NAME)],Args:[],WorkingDir:,Ports:[]ContainerPort{},Env:[]EnvVar{EnvVar{Name:NODE_NAME,Value:,ValueFrom:&EnvVarSource{FieldRef:&ObjectFieldSelector{APIVersion:v1,FieldPath:spec.nodeName,},ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:nil,},},},Resources:ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{},},VolumeMounts:[]VolumeMount{VolumeMount{Name:kube-proxy,ReadOnly:false,MountPath:/var/lib/kube-proxy,SubPath:,MountPropagation:nil,SubPathExpr:,},VolumeMount{Name:xtables-lock,ReadOnly:false,MountPath:/run/xtables.lock,SubPath:,MountPropagation:nil,SubPathExpr:,},VolumeMount{Name:lib-modules,ReadOnly:true,MountPath:/lib/modules,SubPath:,MountPropagation:nil,SubPathExpr:,},VolumeMount{Name:kube-api-access-4s65b,ReadOnly:true,MountPath:/var/run/secrets/kubernetes.io/serviceaccount,SubPath:,MountPropagation:nil,SubPathExpr:,},},LivenessProbe:nil,ReadinessProbe:nil,Lifecycle:nil,TerminationMessagePath:/dev/termination-log,ImagePullPolicy:IfNotPresent,SecurityContext:&SecurityContext{Capabilities:nil,Privileged:*true,SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:nil,ReadOnlyRootFilesystem:nil,AllowPrivilegeEscalation:nil,RunAsGroup:nil,ProcMount:nil,WindowsOptions:nil,SeccompProfile:nil,},Stdin:false,StdinOnce:false,TTY:false,EnvFrom:[]EnvFromSource{},TerminationMessagePolicy:File,VolumeDevices:[]VolumeDevice{},StartupProbe:nil,} start failed in pod kube-proxy-49wc9_kube-system(d21054b8-786d-478b-8623-dea1610e417c): CreateContainerConfigError: services have not yet been read at least once, cannot construct envvars
Sep 20 04:56:25 kind-worker2 kubelet[300]: E0920 04:56:25.898589     300 pod_workers.go:951] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"kube-proxy\" with CreateContainerConfigError: \"services have not yet been read at least once, cannot construct envvars\"" pod="kube-system/kube-proxy-49wc9" podUID=d21054b8-786d-478b-8623-dea1610e417c
Sep 20 04:56:27 kind-worker2 kubelet[300]: E0920 04:56:27.340404     300 kubelet.go:2349] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
Sep 20 04:56:32 kind-worker2 kubelet[300]: E0920 04:56:32.342201     300 kubelet.go:2349] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
Sep 20 04:56:37 kind-worker2 kubelet[300]: E0920 04:56:37.343451     300 kubelet.go:2349] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
Sep 20 04:58:16 kind-worker2 kubelet[300]: I0920 04:58:16.576645     300 topology_manager.go:200] "Topology Admit Handler"
Sep 20 04:58:16 kind-worker2 kubelet[300]: I0920 04:58:16.593016     300 reconciler.go:342] "operationExecutor.VerifyControllerAttachedVolume started for volume \"tmp-dir\" (UniqueName: \"kubernetes.io/empty-dir/7399274e-1056-49e2-90a4-58b992084f52-tmp-dir\") pod \"metrics-server-8cc45cd8d-9n7mg\" (UID: \"7399274e-1056-49e2-90a4-58b992084f52\") " pod="kube-system/metrics-server-8cc45cd8d-9n7mg"
Sep 20 04:58:16 kind-worker2 kubelet[300]: I0920 04:58:16.593300     300 reconciler.go:342] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kube-api-access-z2sdn\" (UniqueName: \"kubernetes.io/projected/7399274e-1056-49e2-90a4-58b992084f52-kube-api-access-z2sdn\") pod \"metrics-server-8cc45cd8d-9n7mg\" (UID: \"7399274e-1056-49e2-90a4-58b992084f52\") " pod="kube-system/metrics-server-8cc45cd8d-9n7mg"
Sep 20 04:58:32 kind-worker2 kubelet[300]: I0920 04:58:32.007627     300 log.go:195] http: TLS handshake error from 10.244.1.2:58458: remote error: tls: bad certificate
Sep 20 04:58:47 kind-worker2 kubelet[300]: I0920 04:58:47.008762     300 log.go:195] http: TLS handshake error from 10.244.1.2:58694: remote error: tls: bad certificate
Sep 20 04:59:02 kind-worker2 kubelet[300]: I0920 04:59:02.009774     300 log.go:195] http: TLS handshake error from 10.244.1.2:58944: remote error: tls: bad certificate
Sep 20 04:59:15 kind-worker2 kubelet[300]: I0920 04:59:15.922037     300 reconciler.go:201] "operationExecutor.UnmountVolume started for volume \"tmp-dir\" (UniqueName: \"kubernetes.io/empty-dir/7399274e-1056-49e2-90a4-58b992084f52-tmp-dir\") pod \"7399274e-1056-49e2-90a4-58b992084f52\" (UID: \"7399274e-1056-49e2-90a4-58b992084f52\") "
Sep 20 04:59:15 kind-worker2 kubelet[300]: I0920 04:59:15.922226     300 reconciler.go:201] "operationExecutor.UnmountVolume started for volume \"kube-api-access-z2sdn\" (UniqueName: \"kubernetes.io/projected/7399274e-1056-49e2-90a4-58b992084f52-kube-api-access-z2sdn\") pod \"7399274e-1056-49e2-90a4-58b992084f52\" (UID: \"7399274e-1056-49e2-90a4-58b992084f52\") "
Sep 20 04:59:15 kind-worker2 kubelet[300]: W0920 04:59:15.922664     300 empty_dir.go:519] Warning: Failed to clear quota on /var/lib/kubelet/pods/7399274e-1056-49e2-90a4-58b992084f52/volumes/kubernetes.io~empty-dir/tmp-dir: clearQuota called, but quotas disabled
Sep 20 04:59:15 kind-worker2 kubelet[300]: I0920 04:59:15.923010     300 operation_generator.go:863] UnmountVolume.TearDown succeeded for volume "kubernetes.io/empty-dir/7399274e-1056-49e2-90a4-58b992084f52-tmp-dir" (OuterVolumeSpecName: "tmp-dir") pod "7399274e-1056-49e2-90a4-58b992084f52" (UID: "7399274e-1056-49e2-90a4-58b992084f52"). InnerVolumeSpecName "tmp-dir". PluginName "kubernetes.io/empty-dir", VolumeGidValue ""
Sep 20 04:59:15 kind-worker2 kubelet[300]: I0920 04:59:15.941977     300 operation_generator.go:863] UnmountVolume.TearDown succeeded for volume "kubernetes.io/projected/7399274e-1056-49e2-90a4-58b992084f52-kube-api-access-z2sdn" (OuterVolumeSpecName: "kube-api-access-z2sdn") pod "7399274e-1056-49e2-90a4-58b992084f52" (UID: "7399274e-1056-49e2-90a4-58b992084f52"). InnerVolumeSpecName "kube-api-access-z2sdn". PluginName "kubernetes.io/projected", VolumeGidValue ""
Sep 20 04:59:16 kind-worker2 kubelet[300]: I0920 04:59:16.023237     300 reconciler.go:384] "Volume detached for volume \"tmp-dir\" (UniqueName: \"kubernetes.io/empty-dir/7399274e-1056-49e2-90a4-58b992084f52-tmp-dir\") on node \"kind-worker2\" DevicePath \"\""
Sep 20 04:59:16 kind-worker2 kubelet[300]: I0920 04:59:16.023328     300 reconciler.go:384] "Volume detached for volume \"kube-api-access-z2sdn\" (UniqueName: \"kubernetes.io/projected/7399274e-1056-49e2-90a4-58b992084f52-kube-api-access-z2sdn\") on node \"kind-worker2\" DevicePath \"\""
Sep 20 04:59:16 kind-worker2 kubelet[300]: I0920 04:59:16.436914     300 scope.go:110] "RemoveContainer" containerID="bd76ea3231e0c655e3a110ae9f1a15cfd72de4cef6e726f44c2f061418e1773c"
Sep 20 04:59:17 kind-worker2 kubelet[300]: I0920 04:59:17.739920     300 kubelet_volumes.go:160] "Cleaned up orphaned pod volumes dir" podUID=7399274e-1056-49e2-90a4-58b992084f52 path="/var/lib/kubelet/pods/7399274e-1056-49e2-90a4-58b992084f52/volumes"
Sep 20 05:02:19 kind-worker2 kubelet[300]: I0920 05:02:19.638535     300 topology_manager.go:200] "Topology Admit Handler"
Sep 20 05:02:19 kind-worker2 kubelet[300]: E0920 05:02:19.638830     300 cpu_manager.go:394] "RemoveStaleState: removing container" podUID="7399274e-1056-49e2-90a4-58b992084f52" containerName="metrics-server"
Sep 20 05:02:19 kind-worker2 kubelet[300]: I0920 05:02:19.639060     300 memory_manager.go:345] "RemoveStaleState removing state" podUID="7399274e-1056-49e2-90a4-58b992084f52" containerName="metrics-server"
Sep 20 05:02:19 kind-worker2 kubelet[300]: I0920 05:02:19.821797     300 reconciler.go:342] "operationExecutor.VerifyControllerAttachedVolume started for volume \"policy-volume\" (UniqueName: \"kubernetes.io/configmap/2b3111f7-718e-422d-bf8b-751990c65a01-policy-volume\") pod \"descheduler-6bbbff857b-skmxn\" (UID: \"2b3111f7-718e-422d-bf8b-751990c65a01\") " pod="kube-system/descheduler-6bbbff857b-skmxn"
Sep 20 05:02:19 kind-worker2 kubelet[300]: I0920 05:02:19.822260     300 reconciler.go:342] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kube-api-access-9fsfk\" (UniqueName: \"kubernetes.io/projected/2b3111f7-718e-422d-bf8b-751990c65a01-kube-api-access-9fsfk\") pod \"descheduler-6bbbff857b-skmxn\" (UID: \"2b3111f7-718e-422d-bf8b-751990c65a01\") " pod="kube-system/descheduler-6bbbff857b-skmxn"
Sep 20 05:05:48 kind-worker2 kubelet[300]: I0920 05:05:48.293001     300 topology_manager.go:200] "Topology Admit Handler"
Sep 20 05:05:48 kind-worker2 kubelet[300]: I0920 05:05:48.391806     300 reconciler.go:342] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kube-api-access-kdvlq\" (UniqueName: \"kubernetes.io/projected/ec0e1581-80d4-400d-b5ea-ae35eb3f265a-kube-api-access-kdvlq\") pod \"background-1-8449dbdffd-5cz7j\" (UID: \"ec0e1581-80d4-400d-b5ea-ae35eb3f265a\") " pod="default/background-1-8449dbdffd-5cz7j"
Sep 20 05:05:57 kind-worker2 kubelet[300]: I0920 05:05:57.396133     300 topology_manager.go:200] "Topology Admit Handler"
Sep 20 05:05:57 kind-worker2 kubelet[300]: I0920 05:05:57.465491     300 reconciler.go:342] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kube-api-access-6nlsv\" (UniqueName: \"kubernetes.io/projected/3c57bc75-867b-4e84-b397-caf3b0ba9684-kube-api-access-6nlsv\") pod \"nginx-deployment-6dccd8f6b9-jssw7\" (UID: \"3c57bc75-867b-4e84-b397-caf3b0ba9684\") " pod="default/nginx-deployment-6dccd8f6b9-jssw7"
Sep 20 05:05:58 kind-worker2 kubelet[300]: I0920 05:05:58.710472     300 pod_container_deletor.go:79] "Container not found in pod's containers" containerID="b89ecb218e9cff9a17686d5031d24d68d5d846eb2c4487263e28432f00b6d224"
Sep 20 05:05:58 kind-worker2 kubelet[300]: I0920 05:05:58.805820     300 reconciler.go:201] "operationExecutor.UnmountVolume started for volume \"policy-volume\" (UniqueName: \"kubernetes.io/configmap/2b3111f7-718e-422d-bf8b-751990c65a01-policy-volume\") pod \"2b3111f7-718e-422d-bf8b-751990c65a01\" (UID: \"2b3111f7-718e-422d-bf8b-751990c65a01\") "
Sep 20 05:05:58 kind-worker2 kubelet[300]: I0920 05:05:58.805987     300 reconciler.go:201] "operationExecutor.UnmountVolume started for volume \"kube-api-access-9fsfk\" (UniqueName: \"kubernetes.io/projected/2b3111f7-718e-422d-bf8b-751990c65a01-kube-api-access-9fsfk\") pod \"2b3111f7-718e-422d-bf8b-751990c65a01\" (UID: \"2b3111f7-718e-422d-bf8b-751990c65a01\") "
Sep 20 05:05:58 kind-worker2 kubelet[300]: W0920 05:05:58.806719     300 empty_dir.go:519] Warning: Failed to clear quota on /var/lib/kubelet/pods/2b3111f7-718e-422d-bf8b-751990c65a01/volumes/kubernetes.io~configmap/policy-volume: clearQuota called, but quotas disabled
Sep 20 05:05:58 kind-worker2 kubelet[300]: I0920 05:05:58.807366     300 operation_generator.go:863] UnmountVolume.TearDown succeeded for volume "kubernetes.io/configmap/2b3111f7-718e-422d-bf8b-751990c65a01-policy-volume" (OuterVolumeSpecName: "policy-volume") pod "2b3111f7-718e-422d-bf8b-751990c65a01" (UID: "2b3111f7-718e-422d-bf8b-751990c65a01"). InnerVolumeSpecName "policy-volume". PluginName "kubernetes.io/configmap", VolumeGidValue ""
Sep 20 05:05:58 kind-worker2 kubelet[300]: I0920 05:05:58.838876     300 operation_generator.go:863] UnmountVolume.TearDown succeeded for volume "kubernetes.io/projected/2b3111f7-718e-422d-bf8b-751990c65a01-kube-api-access-9fsfk" (OuterVolumeSpecName: "kube-api-access-9fsfk") pod "2b3111f7-718e-422d-bf8b-751990c65a01" (UID: "2b3111f7-718e-422d-bf8b-751990c65a01"). InnerVolumeSpecName "kube-api-access-9fsfk". PluginName "kubernetes.io/projected", VolumeGidValue ""
Sep 20 05:05:58 kind-worker2 kubelet[300]: I0920 05:05:58.908906     300 reconciler.go:384] "Volume detached for volume \"kube-api-access-9fsfk\" (UniqueName: \"kubernetes.io/projected/2b3111f7-718e-422d-bf8b-751990c65a01-kube-api-access-9fsfk\") on node \"kind-worker2\" DevicePath \"\""
Sep 20 05:05:58 kind-worker2 kubelet[300]: I0920 05:05:58.909006     300 reconciler.go:384] "Volume detached for volume \"policy-volume\" (UniqueName: \"kubernetes.io/configmap/2b3111f7-718e-422d-bf8b-751990c65a01-policy-volume\") on node \"kind-worker2\" DevicePath \"\""
Sep 20 05:06:01 kind-worker2 kubelet[300]: I0920 05:06:01.745251     300 kubelet_volumes.go:160] "Cleaned up orphaned pod volumes dir" podUID=2b3111f7-718e-422d-bf8b-751990c65a01 path="/var/lib/kubelet/pods/2b3111f7-718e-422d-bf8b-751990c65a01/volumes"
Sep 20 05:06:06 kind-worker2 kubelet[300]: I0920 05:06:06.992335     300 scope.go:110] "RemoveContainer" containerID="ca36d9705264b11bf0012cc984044ebaa870cf23c84558a8884ff42b70bd31e3"
Sep 20 05:07:21 kind-worker2 kubelet[300]: I0920 05:07:21.653429     300 reconciler.go:201] "operationExecutor.UnmountVolume started for volume \"kube-api-access-6nlsv\" (UniqueName: \"kubernetes.io/projected/3c57bc75-867b-4e84-b397-caf3b0ba9684-kube-api-access-6nlsv\") pod \"3c57bc75-867b-4e84-b397-caf3b0ba9684\" (UID: \"3c57bc75-867b-4e84-b397-caf3b0ba9684\") "
Sep 20 05:07:21 kind-worker2 kubelet[300]: I0920 05:07:21.653602     300 reconciler.go:201] "operationExecutor.UnmountVolume started for volume \"kube-api-access-kdvlq\" (UniqueName: \"kubernetes.io/projected/ec0e1581-80d4-400d-b5ea-ae35eb3f265a-kube-api-access-kdvlq\") pod \"ec0e1581-80d4-400d-b5ea-ae35eb3f265a\" (UID: \"ec0e1581-80d4-400d-b5ea-ae35eb3f265a\") "
Sep 20 05:07:21 kind-worker2 kubelet[300]: I0920 05:07:21.678016     300 operation_generator.go:863] UnmountVolume.TearDown succeeded for volume "kubernetes.io/projected/ec0e1581-80d4-400d-b5ea-ae35eb3f265a-kube-api-access-kdvlq" (OuterVolumeSpecName: "kube-api-access-kdvlq") pod "ec0e1581-80d4-400d-b5ea-ae35eb3f265a" (UID: "ec0e1581-80d4-400d-b5ea-ae35eb3f265a"). InnerVolumeSpecName "kube-api-access-kdvlq". PluginName "kubernetes.io/projected", VolumeGidValue ""
Sep 20 05:07:21 kind-worker2 kubelet[300]: I0920 05:07:21.686255     300 operation_generator.go:863] UnmountVolume.TearDown succeeded for volume "kubernetes.io/projected/3c57bc75-867b-4e84-b397-caf3b0ba9684-kube-api-access-6nlsv" (OuterVolumeSpecName: "kube-api-access-6nlsv") pod "3c57bc75-867b-4e84-b397-caf3b0ba9684" (UID: "3c57bc75-867b-4e84-b397-caf3b0ba9684"). InnerVolumeSpecName "kube-api-access-6nlsv". PluginName "kubernetes.io/projected", VolumeGidValue ""
Sep 20 05:07:21 kind-worker2 kubelet[300]: I0920 05:07:21.754543     300 reconciler.go:384] "Volume detached for volume \"kube-api-access-kdvlq\" (UniqueName: \"kubernetes.io/projected/ec0e1581-80d4-400d-b5ea-ae35eb3f265a-kube-api-access-kdvlq\") on node \"kind-worker2\" DevicePath \"\""
Sep 20 05:07:21 kind-worker2 kubelet[300]: I0920 05:07:21.754653     300 reconciler.go:384] "Volume detached for volume \"kube-api-access-6nlsv\" (UniqueName: \"kubernetes.io/projected/3c57bc75-867b-4e84-b397-caf3b0ba9684-kube-api-access-6nlsv\") on node \"kind-worker2\" DevicePath \"\""
Sep 20 05:07:22 kind-worker2 kubelet[300]: I0920 05:07:22.075664     300 scope.go:110] "RemoveContainer" containerID="0af3ff5ffdb8663b6ed696ba195e5918dd86396e1f9373255ae1f943bb37315f"
Sep 20 05:07:22 kind-worker2 kubelet[300]: I0920 05:07:22.403914     300 scope.go:110] "RemoveContainer" containerID="06b08f51e8a074a056d2048cfd146e590543a9e8195a8a9f0c594af0723fa4b7"
Sep 20 05:07:23 kind-worker2 kubelet[300]: I0920 05:07:23.748450     300 kubelet_volumes.go:160] "Cleaned up orphaned pod volumes dir" podUID=3c57bc75-867b-4e84-b397-caf3b0ba9684 path="/var/lib/kubelet/pods/3c57bc75-867b-4e84-b397-caf3b0ba9684/volumes"
Sep 20 05:07:23 kind-worker2 kubelet[300]: I0920 05:07:23.749687     300 kubelet_volumes.go:160] "Cleaned up orphaned pod volumes dir" podUID=ec0e1581-80d4-400d-b5ea-ae35eb3f265a path="/var/lib/kubelet/pods/ec0e1581-80d4-400d-b5ea-ae35eb3f265a/volumes"
Sep 20 05:08:26 kind-worker2 kubelet[300]: I0920 05:08:26.199453     300 topology_manager.go:200] "Topology Admit Handler"
Sep 20 05:08:26 kind-worker2 kubelet[300]: E0920 05:08:26.199692     300 cpu_manager.go:394] "RemoveStaleState: removing container" podUID="2b3111f7-718e-422d-bf8b-751990c65a01" containerName="descheduler"
Sep 20 05:08:26 kind-worker2 kubelet[300]: E0920 05:08:26.199753     300 cpu_manager.go:394] "RemoveStaleState: removing container" podUID="ec0e1581-80d4-400d-b5ea-ae35eb3f265a" containerName="nginx"
Sep 20 05:08:26 kind-worker2 kubelet[300]: E0920 05:08:26.199797     300 cpu_manager.go:394] "RemoveStaleState: removing container" podUID="3c57bc75-867b-4e84-b397-caf3b0ba9684" containerName="nginx"
Sep 20 05:08:26 kind-worker2 kubelet[300]: I0920 05:08:26.199923     300 memory_manager.go:345] "RemoveStaleState removing state" podUID="2b3111f7-718e-422d-bf8b-751990c65a01" containerName="descheduler"
Sep 20 05:08:26 kind-worker2 kubelet[300]: I0920 05:08:26.199972     300 memory_manager.go:345] "RemoveStaleState removing state" podUID="ec0e1581-80d4-400d-b5ea-ae35eb3f265a" containerName="nginx"
Sep 20 05:08:26 kind-worker2 kubelet[300]: I0920 05:08:26.200011     300 memory_manager.go:345] "RemoveStaleState removing state" podUID="3c57bc75-867b-4e84-b397-caf3b0ba9684" containerName="nginx"
Sep 20 05:08:26 kind-worker2 kubelet[300]: I0920 05:08:26.315252     300 reconciler.go:342] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kube-api-access-lt6rz\" (UniqueName: \"kubernetes.io/projected/46e552c0-22d9-41ed-8349-f7d2f2bb5dba-kube-api-access-lt6rz\") pod \"descheduler-6bbbff857b-frmh7\" (UID: \"46e552c0-22d9-41ed-8349-f7d2f2bb5dba\") " pod="kube-system/descheduler-6bbbff857b-frmh7"
Sep 20 05:08:26 kind-worker2 kubelet[300]: I0920 05:08:26.315525     300 reconciler.go:342] "operationExecutor.VerifyControllerAttachedVolume started for volume \"policy-volume\" (UniqueName: \"kubernetes.io/configmap/46e552c0-22d9-41ed-8349-f7d2f2bb5dba-policy-volume\") pod \"descheduler-6bbbff857b-frmh7\" (UID: \"46e552c0-22d9-41ed-8349-f7d2f2bb5dba\") " pod="kube-system/descheduler-6bbbff857b-frmh7"
Sep 20 05:08:42 kind-worker2 kubelet[300]: I0920 05:08:42.260359     300 reconciler.go:201] "operationExecutor.UnmountVolume started for volume \"policy-volume\" (UniqueName: \"kubernetes.io/configmap/46e552c0-22d9-41ed-8349-f7d2f2bb5dba-policy-volume\") pod \"46e552c0-22d9-41ed-8349-f7d2f2bb5dba\" (UID: \"46e552c0-22d9-41ed-8349-f7d2f2bb5dba\") "
Sep 20 05:08:42 kind-worker2 kubelet[300]: I0920 05:08:42.260557     300 reconciler.go:201] "operationExecutor.UnmountVolume started for volume \"kube-api-access-lt6rz\" (UniqueName: \"kubernetes.io/projected/46e552c0-22d9-41ed-8349-f7d2f2bb5dba-kube-api-access-lt6rz\") pod \"46e552c0-22d9-41ed-8349-f7d2f2bb5dba\" (UID: \"46e552c0-22d9-41ed-8349-f7d2f2bb5dba\") "
Sep 20 05:08:42 kind-worker2 kubelet[300]: W0920 05:08:42.260897     300 empty_dir.go:519] Warning: Failed to clear quota on /var/lib/kubelet/pods/46e552c0-22d9-41ed-8349-f7d2f2bb5dba/volumes/kubernetes.io~configmap/policy-volume: clearQuota called, but quotas disabled
Sep 20 05:08:42 kind-worker2 kubelet[300]: I0920 05:08:42.261600     300 operation_generator.go:863] UnmountVolume.TearDown succeeded for volume "kubernetes.io/configmap/46e552c0-22d9-41ed-8349-f7d2f2bb5dba-policy-volume" (OuterVolumeSpecName: "policy-volume") pod "46e552c0-22d9-41ed-8349-f7d2f2bb5dba" (UID: "46e552c0-22d9-41ed-8349-f7d2f2bb5dba"). InnerVolumeSpecName "policy-volume". PluginName "kubernetes.io/configmap", VolumeGidValue ""
Sep 20 05:08:42 kind-worker2 kubelet[300]: I0920 05:08:42.286085     300 operation_generator.go:863] UnmountVolume.TearDown succeeded for volume "kubernetes.io/projected/46e552c0-22d9-41ed-8349-f7d2f2bb5dba-kube-api-access-lt6rz" (OuterVolumeSpecName: "kube-api-access-lt6rz") pod "46e552c0-22d9-41ed-8349-f7d2f2bb5dba" (UID: "46e552c0-22d9-41ed-8349-f7d2f2bb5dba"). InnerVolumeSpecName "kube-api-access-lt6rz". PluginName "kubernetes.io/projected", VolumeGidValue ""
Sep 20 05:08:42 kind-worker2 kubelet[300]: I0920 05:08:42.361048     300 reconciler.go:384] "Volume detached for volume \"policy-volume\" (UniqueName: \"kubernetes.io/configmap/46e552c0-22d9-41ed-8349-f7d2f2bb5dba-policy-volume\") on node \"kind-worker2\" DevicePath \"\""
Sep 20 05:08:42 kind-worker2 kubelet[300]: I0920 05:08:42.361158     300 reconciler.go:384] "Volume detached for volume \"kube-api-access-lt6rz\" (UniqueName: \"kubernetes.io/projected/46e552c0-22d9-41ed-8349-f7d2f2bb5dba-kube-api-access-lt6rz\") on node \"kind-worker2\" DevicePath \"\""
Sep 20 05:08:42 kind-worker2 kubelet[300]: I0920 05:08:42.412859     300 scope.go:110] "RemoveContainer" containerID="fd9df42acba9316f804eaa90f7ee0105c4fe3e1fe5346be162492dfa94d768d3"
Sep 20 05:08:43 kind-worker2 kubelet[300]: I0920 05:08:43.284585     300 topology_manager.go:200] "Topology Admit Handler"
Sep 20 05:08:43 kind-worker2 kubelet[300]: E0920 05:08:43.284711     300 cpu_manager.go:394] "RemoveStaleState: removing container" podUID="46e552c0-22d9-41ed-8349-f7d2f2bb5dba" containerName="descheduler"
Sep 20 05:08:43 kind-worker2 kubelet[300]: I0920 05:08:43.284789     300 memory_manager.go:345] "RemoveStaleState removing state" podUID="46e552c0-22d9-41ed-8349-f7d2f2bb5dba" containerName="descheduler"
Sep 20 05:08:43 kind-worker2 kubelet[300]: I0920 05:08:43.474355     300 reconciler.go:342] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kube-api-access-pstjp\" (UniqueName: \"kubernetes.io/projected/fbf27972-5c75-440a-9c2d-d049173f0263-kube-api-access-pstjp\") pod \"background-1-8449dbdffd-54vvv\" (UID: \"fbf27972-5c75-440a-9c2d-d049173f0263\") " pod="default/background-1-8449dbdffd-54vvv"
Sep 20 05:08:43 kind-worker2 kubelet[300]: I0920 05:08:43.745119     300 kubelet_volumes.go:160] "Cleaned up orphaned pod volumes dir" podUID=46e552c0-22d9-41ed-8349-f7d2f2bb5dba path="/var/lib/kubelet/pods/46e552c0-22d9-41ed-8349-f7d2f2bb5dba/volumes"
Sep 20 05:08:48 kind-worker2 kubelet[300]: I0920 05:08:48.976016     300 topology_manager.go:200] "Topology Admit Handler"
Sep 20 05:08:49 kind-worker2 kubelet[300]: I0920 05:08:49.126537     300 reconciler.go:342] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kube-api-access-rlbd4\" (UniqueName: \"kubernetes.io/projected/1d7c9e9e-7daa-4a28-bc57-e96ae77d8258-kube-api-access-rlbd4\") pod \"nginx-deployment-6dccd8f6b9-dx5ww\" (UID: \"1d7c9e9e-7daa-4a28-bc57-e96ae77d8258\") " pod="default/nginx-deployment-6dccd8f6b9-dx5ww"
